config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "oficios#index"
  resources :oficios, except: [:index]

  get 'signup', to: "usuarios#new"
  resources :usuarios, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # Defines the root path route ("/")
  # root "articles#index"
  #resources :articles
  #resources :users, except: [:new]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/oficio.rb
class Oficio < ApplicationRecord
    validates :titulo, presence: true, length:{minimum: 5, maximum: 100}
    validates :descripcion, presence: true, length:{minimum: 10, maximum: 350}
    belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_many :oficios

    before_save {self.email = email.downcase}
    validates :nombre, presence: true, length:{minimum: 3, maximum: 70}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, 
                uniqueness:{case_sensitive: false}, 
                length:{maximum:105},
                format:{with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oficios_controller.rb
class OficiosController < ApplicationController

    def index
        @oficios = Oficio.all
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = Usuario.find_by(email: params[:session][:email].downcase)

        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to root_path
        else
            flash.now[:alert] = "There is something wrong with your credentials"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out successfully"
        redirect_to root_path
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

    def new
        @user = Usuario.new        
    end

    def create
        @user = Usuario.new(properties)
        if @user.save
            #flash[:notice] = "Bienvenido #{@user.username}!"
            redirect_to "/"
        else
            render 'new'
        end     
    end

    def show
        @user = Usuario.find(params[:id])
    end
    private
    def properties
        params.require(:usuario).permit(:nombre, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oficios_helper.rb
module OficiosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OficiosApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "partials/nav"%>
    <%= yield %>
  <%= render "partials/footer"%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/oficios/index.html.erb
<div class="container">
    <h1 class="text-center mt-5">¿Necesitas Un Profesional?</h1>
    <div class="row mt-5">
        <div class="col">
            <select class="form-select" aria-label="Default select example">
                <option selected>Categoria</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>
        <div class="col">
            <select class="form-select" aria-label="Default select example">
                <option selected>Región</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>
        <div class="col">
            <button class="btn btn-outline-primary w-100">Buscar</button>
        </div>
    </div>

    <%@oficios.each do |oficio|%>
        <div class="bg-white rounded shadow d-flex p-4 gap-5 mt-5 mb-5">
            <img src="/user.png" alt="usuario-profile.png" class="mini-profile">
            <div>
                <h1><%=oficio.usuario.nombre%></h1>
                <p><%=oficio.titulo%></p>
            </div>
        </div>
    <%end%>
</div>

app/views/partials/_footer.html.erb
<div class="bg-dark footer text-white">
        <p>Copyright © <%=Time.now.year%></p>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "OficiosApp", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto me-5">
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", login_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Registrarse", signup_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/usuarios/new.html.erb
<div class="container">
    <h1 class="text-center mt-5">Crea tú cuenta y comienza a crear avisos</h1>

    <%if @user.errors.any?%>
    <div class="alert alert-danger" role="alert">
        The following errors prevent the account from being created
        <ul>
            <%@user.errors.full_messages.each do |msg|%>
                <li><%=msg%></li>
            <%end%>
        </ul>
        </div>
    <%end%>

    
    <%= form_with(model: @user, local: true , data: {turbo: false}, class: "w-90 m-auto bg-secondary bg-gradient rounded p-5 text-white mt-5 mb-5 shadow") do |f|%>
    <div class="row">
    <div class="col-2 fw-bold">
        <%= f.label :nombre%>
    </div>
    <div class="col-12">
        <%= f.text_field :nombre, class:"w-100 rounded border-0 p-2", placeholder: "Ingresa tú nombre"%>  
    </div>
    
    
    </div>
    <div class="row mt-5">
        <div class="col-2 fw-bold">
            <%= f.label :email%>    
        </div>
        <div class="col-12">
            <%= f.email_field :email, class:"w-100 rounded border-0 p-2", placeholder: "Ingresa tú email"%>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-2 fw-bold">
            <%= f.label :password%>    
        </div>
        <div class="col-12">
            <%= f.password_field :password, class:"w-100 rounded border-0 p-2", placeholder: "Crea una contraseña" %>
        </div>
    </div>
    <div class="text-center mt-5">
    <%= f.submit "Crear Cuenta", class:"p-2 btn btn-outline-light"%>
    </div>
    <%end%>
</div>

app/views/usuarios/show.html.erb
<div class="container text-center mt-5">
    <div class="bg-white shadow w-50 m-auto p-3 rounded">
    <img src="/user.png" alt="profile.png" class="profile-pic">

    <h1 class="mt-3">
        <%=@user.nombre%>
    </h1>
    </div>
    <h3 class="mt-5">Avisos Creados</h3>
</div>